const shared = {
  targetRPE: 8,
  recommendedWeight: null,
};

function exercise({
  id,
  name,
  category,
  equipment,
  muscleGroup,
  priority,
  progressionType,
  sets,
  repsMin,
  repsMax,
  repsLabel,
  restSeconds,
  loadType = "external",
  weightMode = "kg",
  incrementKg,
  roundToKg,
  targetRPE = shared.targetRPE,
  recommendedWeight = shared.recommendedWeight,
  notes = "",
}) {
  const entry = {
    id,
    name,
    category,
    equipment,
    muscleGroup,
    priority,
    progressionType,
    sets,
    repsMin,
    repsMax,
    repsLabel,
    targetRPE,
    restSeconds,
    recommendedWeight,
    loadType,
    weightMode,
    incrementKg,
    roundToKg,
  };

  if (notes) {
    entry.notes = notes;
  }

  return entry;
}

export const workoutProgram = {
  name: "Athletic Bodybuilding RPE Program",
  version: "2.0.0",
  cycleOrder: ["day-1", "day-2", "day-3", "day-4", "day-5"],
  days: [
    {
      id: "day-1",
      name: "Day 1 — Chest + Back Power",
      shortName: "Day 1",
      focus: "Chest + Back Power",
      type: "training",
      warmup: {
        title: "Warm-up & Activation",
        items: [
          {
            id: "day-1-warmup-light-cardio",
            name: "Light cardio",
            prescription: "3-5 min",
            notes: "Easy pace, raise body temperature.",
            videoUrl: "",
          },
          {
            id: "day-1-warmup-band-pull-aparts",
            name: "Band pull-aparts",
            prescription: "2 x 15",
            notes: "Open shoulders and wake up upper back before pressing.",
            videoUrl: "",
          },
        ],
      },
      exercises: [
        exercise({
          id: "bench-press",
          name: "Bench Press",
          category: "compound",
          equipment: "barbell",
          muscleGroup: "Chest",
          priority: "high",
          progressionType: "strength",
          sets: 4,
          repsMin: 5,
          repsMax: 7,
          repsLabel: "5–7",
          restSeconds: 180,
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "weighted-pull-ups",
          name: "Weighted Pull-Ups",
          category: "compound",
          equipment: "bodyweight",
          muscleGroup: "Lats / Back Width",
          priority: "high",
          progressionType: "strength",
          sets: 4,
          repsMin: 6,
          repsMax: 8,
          repsLabel: "6–8",
          restSeconds: [150, 180],
          loadType: "optionalExternal",
          weightMode: "additional load",
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "incline-dumbbell-press",
          name: "Incline Dumbbell Press",
          category: "compound",
          equipment: "dumbbell",
          muscleGroup: "Upper Chest",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 4,
          repsMin: 8,
          repsMax: 10,
          repsLabel: "8–10",
          restSeconds: 120,
          weightMode: "per dumbbell",
          incrementKg: 2,
          roundToKg: 1,
        }),
        exercise({
          id: "chest-supported-row",
          name: "Chest Supported Row",
          category: "compound",
          equipment: "machine",
          muscleGroup: "Upper Back",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 4,
          repsMin: 8,
          repsMax: 10,
          repsLabel: "8–10",
          restSeconds: 120,
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "machine-chest-press",
          name: "Machine Chest Press",
          category: "compound",
          equipment: "machine",
          muscleGroup: "Chest",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10–12",
          restSeconds: 90,
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "lat-pulldown",
          name: "Lat Pulldown",
          category: "compound",
          equipment: "cable",
          muscleGroup: "Lats / Back Width",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10–12",
          restSeconds: 90,
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "dips",
          name: "Dips",
          category: "compound",
          equipment: "bodyweight",
          muscleGroup: "Chest / Triceps",
          priority: "medium",
          progressionType: "hypertrophy",
          sets: 2,
          repsMin: null,
          repsMax: null,
          repsLabel: "failure",
          restSeconds: 120,
          loadType: "optionalExternal",
          weightMode: "additional load",
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "hanging-leg-raise",
          name: "Hanging Leg Raise",
          category: "core",
          equipment: "bodyweight",
          muscleGroup: "Core",
          priority: "medium",
          progressionType: "core",
          sets: 3,
          repsMin: 12,
          repsMax: 15,
          repsLabel: "12–15",
          restSeconds: 45,
          loadType: "bodyweight",
        }),
        exercise({
          id: "cable-crunch",
          name: "Cable Crunch",
          category: "core",
          equipment: "cable",
          muscleGroup: "Core",
          priority: "medium",
          progressionType: "core",
          sets: 3,
          repsMin: 15,
          repsMax: 15,
          repsLabel: "15",
          restSeconds: 45,
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
      ],
    },
    {
      id: "day-2",
      name: "Day 2 — Athletic Lower + Vertical",
      shortName: "Day 2",
      focus: "Athletic Lower + Vertical",
      type: "training",
      exercises: [
        exercise({
          id: "pogo-jumps",
          name: "Pogo Jumps",
          category: "athletic",
          equipment: "bodyweight",
          muscleGroup: "Ankles / Elasticity",
          priority: "medium",
          progressionType: "athletic",
          sets: 3,
          repsMin: 20,
          repsMax: 20,
          repsLabel: "20",
          restSeconds: 60,
          loadType: "bodyweight",
        }),
        exercise({
          id: "box-jumps",
          name: "Box Jumps",
          category: "athletic",
          equipment: "bodyweight",
          muscleGroup: "Vertical Power",
          priority: "high",
          progressionType: "athletic",
          sets: 4,
          repsMin: 3,
          repsMax: 3,
          repsLabel: "3",
          restSeconds: 90,
          loadType: "bodyweight",
        }),
        exercise({
          id: "hang-cleans",
          name: "Hang Cleans",
          category: "athletic",
          equipment: "barbell",
          muscleGroup: "Full Body Power",
          priority: "high",
          progressionType: "athletic",
          sets: 4,
          repsMin: 3,
          repsMax: 5,
          repsLabel: "3–5",
          restSeconds: [120, 180],
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "bulgarian-split-squat",
          name: "Bulgarian Split Squat",
          category: "compound",
          equipment: "dumbbell",
          muscleGroup: "Quads / Glutes",
          priority: "medium",
          progressionType: "hypertrophy",
          sets: 4,
          repsMin: 8,
          repsMax: 8,
          repsLabel: "8",
          restSeconds: 120,
          weightMode: "per dumbbell",
          incrementKg: 2,
          roundToKg: 1,
        }),
        exercise({
          id: "romanian-deadlift",
          name: "Romanian Deadlift",
          category: "compound",
          equipment: "barbell",
          muscleGroup: "Hamstrings / Glutes",
          priority: "medium",
          progressionType: "hypertrophy",
          sets: 4,
          repsMin: 8,
          repsMax: 8,
          repsLabel: "8",
          restSeconds: [120, 180],
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "hack-squat",
          name: "Hack Squat",
          category: "compound",
          equipment: "machine",
          muscleGroup: "Quads",
          priority: "medium",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 10,
          repsLabel: "10",
          restSeconds: 120,
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "hamstring-curl",
          name: "Hamstring Curl",
          category: "isolation",
          equipment: "machine",
          muscleGroup: "Hamstrings",
          priority: "medium",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10–12",
          restSeconds: 90,
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "standing-calf-raise",
          name: "Standing Calf Raise",
          category: "isolation",
          equipment: "machine",
          muscleGroup: "Calves",
          priority: "medium",
          progressionType: "hypertrophy",
          sets: 4,
          repsMin: 12,
          repsMax: 15,
          repsLabel: "12–15",
          restSeconds: 60,
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "tibialis-raises",
          name: "Tibialis Raises",
          category: "isolation",
          equipment: "bodyweight",
          muscleGroup: "Tibialis",
          priority: "medium",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 15,
          repsMax: 20,
          repsLabel: "15–20",
          restSeconds: 45,
          loadType: "optionalExternal",
          incrementKg: 1,
          roundToKg: 1,
        }),
        exercise({
          id: "copenhagen-plank",
          name: "Copenhagen Plank",
          category: "core",
          equipment: "bodyweight",
          muscleGroup: "Adductors / Core",
          priority: "medium",
          progressionType: "core",
          sets: 3,
          repsMin: null,
          repsMax: null,
          repsLabel: "timed sets",
          restSeconds: 45,
          loadType: "bodyweight",
        }),
      ],
    },
    {
      id: "day-3",
      name: "Day 3 — Rest / Basketball / Mobility",
      shortName: "Day 3",
      focus: "Rest / Basketball / Mobility",
      type: "recovery",
      activities: ["Light Basketball", "Mobility", "Stretching", "Recovery work", "Optional Abs"],
      exercises: [],
    },
    {
      id: "day-4",
      name: "Day 4 — Upper Hypertrophy",
      shortName: "Day 4",
      focus: "Upper Hypertrophy",
      type: "training",
      exercises: [
        exercise({
          id: "incline-smith-press",
          name: "Incline Smith Press",
          category: "compound",
          equipment: "smith",
          muscleGroup: "Upper Chest",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 4,
          repsMin: 8,
          repsMax: 10,
          repsLabel: "8–10",
          restSeconds: 120,
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "flat-dumbbell-press",
          name: "Flat Dumbbell Press",
          category: "compound",
          equipment: "dumbbell",
          muscleGroup: "Chest",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10–12",
          restSeconds: 90,
          weightMode: "per dumbbell",
          incrementKg: 2,
          roundToKg: 1,
        }),
        exercise({
          id: "pec-deck-machine-fly",
          name: "Pec Deck / Machine Fly",
          category: "isolation",
          equipment: "machine",
          muscleGroup: "Chest",
          priority: "high",
          progressionType: "pump",
          sets: 3,
          repsMin: 12,
          repsMax: 15,
          repsLabel: "12–15",
          restSeconds: [60, 75],
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "neutral-grip-lat-pulldown",
          name: "Neutral Grip Lat Pulldown",
          category: "compound",
          equipment: "cable",
          muscleGroup: "Lats / Back Width",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 4,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10–12",
          restSeconds: 90,
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "single-arm-row",
          name: "Single Arm Row",
          category: "compound",
          equipment: "dumbbell",
          muscleGroup: "Back",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 10,
          repsLabel: "10",
          restSeconds: 90,
          weightMode: "per dumbbell",
          incrementKg: 2,
          roundToKg: 1,
        }),
        exercise({
          id: "lateral-raises",
          name: "Lateral Raises",
          category: "isolation",
          equipment: "dumbbell",
          muscleGroup: "Side Delts",
          priority: "high",
          progressionType: "pump",
          sets: 5,
          repsMin: 12,
          repsMax: 15,
          repsLabel: "12–15",
          restSeconds: 60,
          weightMode: "per dumbbell",
          incrementKg: 1,
          roundToKg: 1,
        }),
        exercise({
          id: "rear-delt-fly",
          name: "Rear Delt Fly",
          category: "isolation",
          equipment: "machine",
          muscleGroup: "Rear Delts",
          priority: "high",
          progressionType: "pump",
          sets: 4,
          repsMin: 15,
          repsMax: 15,
          repsLabel: "15",
          restSeconds: 60,
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "ez-bar-curl",
          name: "EZ Bar Curl",
          category: "isolation",
          equipment: "barbell",
          muscleGroup: "Biceps",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 10,
          repsLabel: "10",
          restSeconds: [60, 90],
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "hammer-curl",
          name: "Hammer Curl",
          category: "isolation",
          equipment: "dumbbell",
          muscleGroup: "Biceps / Brachialis",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 12,
          repsMax: 12,
          repsLabel: "12",
          restSeconds: 60,
          weightMode: "per dumbbell",
          incrementKg: 1,
          roundToKg: 1,
        }),
        exercise({
          id: "overhead-tricep-extension",
          name: "Overhead Tricep Extension",
          category: "isolation",
          equipment: "cable",
          muscleGroup: "Triceps",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10–12",
          restSeconds: [60, 75],
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "decline-sit-ups-cable-abs",
          name: "Decline Sit-Ups / Cable Abs",
          category: "core",
          equipment: "bodyweight",
          muscleGroup: "Core",
          priority: "medium",
          progressionType: "core",
          sets: 3,
          repsMin: 15,
          repsMax: 15,
          repsLabel: "15",
          restSeconds: 45,
          loadType: "optionalExternal",
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
      ],
    },
    {
      id: "day-5",
      name: "Day 5 — Arms + Delts + Athletic Upper",
      shortName: "Day 5",
      focus: "Arms + Delts + Athletic Upper",
      type: "training",
      exercises: [
        exercise({
          id: "weighted-dips",
          name: "Weighted Dips",
          category: "compound",
          equipment: "bodyweight",
          muscleGroup: "Triceps / Chest",
          priority: "high",
          progressionType: "strength",
          sets: 4,
          repsMin: 6,
          repsMax: 8,
          repsLabel: "6–8",
          restSeconds: [150, 180],
          loadType: "optionalExternal",
          weightMode: "additional load",
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "chin-ups",
          name: "Chin-Ups",
          category: "compound",
          equipment: "bodyweight",
          muscleGroup: "Lats / Biceps",
          priority: "high",
          progressionType: "strength",
          sets: 4,
          repsMin: 6,
          repsMax: 10,
          repsLabel: "6–10",
          restSeconds: [120, 180],
          loadType: "optionalExternal",
          weightMode: "additional load",
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "seated-dumbbell-shoulder-press",
          name: "Seated Dumbbell Shoulder Press",
          category: "compound",
          equipment: "dumbbell",
          muscleGroup: "Delts",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 4,
          repsMin: 8,
          repsMax: 10,
          repsLabel: "8–10",
          restSeconds: 120,
          weightMode: "per dumbbell",
          incrementKg: 2,
          roundToKg: 1,
        }),
        exercise({
          id: "heavy-lateral-raises",
          name: "Heavy Lateral Raises",
          category: "isolation",
          equipment: "dumbbell",
          muscleGroup: "Side Delts",
          priority: "high",
          progressionType: "pump",
          sets: 4,
          repsMin: 12,
          repsMax: 15,
          repsLabel: "12–15",
          restSeconds: [60, 75],
          weightMode: "per dumbbell",
          incrementKg: 1,
          roundToKg: 1,
        }),
        exercise({
          id: "preacher-curl",
          name: "Preacher Curl",
          category: "isolation",
          equipment: "machine",
          muscleGroup: "Biceps",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10–12",
          restSeconds: [60, 90],
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "incline-dumbbell-curl",
          name: "Incline Dumbbell Curl",
          category: "isolation",
          equipment: "dumbbell",
          muscleGroup: "Biceps",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 12,
          repsMax: 15,
          repsLabel: "12–15",
          restSeconds: 60,
          weightMode: "per dumbbell",
          incrementKg: 1,
          roundToKg: 1,
        }),
        exercise({
          id: "skull-crushers",
          name: "Skull Crushers",
          category: "isolation",
          equipment: "barbell",
          muscleGroup: "Triceps",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10–12",
          restSeconds: [60, 90],
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "rope-overhead-extension",
          name: "Rope Overhead Extension",
          category: "isolation",
          equipment: "cable",
          muscleGroup: "Triceps",
          priority: "high",
          progressionType: "pump",
          sets: 3,
          repsMin: 12,
          repsMax: 15,
          repsLabel: "12–15",
          restSeconds: [45, 75],
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "explosive-push-ups",
          name: "Explosive Push-Ups",
          category: "athletic",
          equipment: "bodyweight",
          muscleGroup: "Upper Power",
          priority: "medium",
          progressionType: "athletic",
          sets: 3,
          repsMin: 5,
          repsMax: 8,
          repsLabel: "5–8",
          restSeconds: [60, 90],
          loadType: "bodyweight",
        }),
        exercise({
          id: "plank",
          name: "Plank",
          category: "core",
          equipment: "bodyweight",
          muscleGroup: "Core",
          priority: "medium",
          progressionType: "core",
          sets: 3,
          repsMin: 60,
          repsMax: 60,
          repsLabel: "60 sec",
          restSeconds: [45, 60],
          loadType: "bodyweight",
        }),
      ],
    },
  ],
};

export const athleticAestheticBasketballProgram = {
  name: "Athletic Aesthetic Basketball Program",
  nickname: "Athletic Aesthetic",
  description: "Upper Focus + Basketball Performance + V-Taper + Strength + Hypertrophy",
  goal: "Upper focus, basketball performance, V-taper, strength, and hypertrophy",
  version: "1.0.0",
  cycleOrder: ["aab-day-1", "aab-day-2", "aab-day-3", "aab-day-4", "aab-day-5", "aab-day-6"],
  days: [
    {
      id: "aab-day-1",
      name: "Day 1 - Chest + Back Power",
      shortName: "Day 1",
      focus: "Chest + Back Power",
      type: "training",
      notes:
        "At Bench Press, do not go to failure. The goal is controlled progression, stable form, and RPE 8-8.5.",
      warmup: {
        title: "Warm-up & Activation",
        items: [
          { id: "aab-day-1-warmup-1", name: "Band Shoulder Pass-Throughs", prescription: "2 x 10", notes: "Rest 30 sec", videoUrl: "" },
          { id: "aab-day-1-warmup-2", name: "Band External Rotations", prescription: "2 x 12 / arm", notes: "Rest 30 sec", videoUrl: "" },
          { id: "aab-day-1-warmup-3", name: "Scapular Push-Ups", prescription: "2 x 10", notes: "Rest 30-45 sec", videoUrl: "" },
          { id: "aab-day-1-warmup-4", name: "Push-Up Plus", prescription: "1-2 x 8", notes: "Rest 30-45 sec", videoUrl: "" },
          { id: "aab-day-1-warmup-5", name: "Bench Press Warm-Up Sets", prescription: "3-4 progressive sets", notes: "Rest 60-90 sec", videoUrl: "" },
        ],
      },
      exercises: [
        exercise({
          id: "bench-press",
          name: "Bench Press",
          category: "compound",
          equipment: "barbell",
          muscleGroup: "Chest",
          priority: "high",
          progressionType: "strength",
          sets: 4,
          repsMin: 5,
          repsMax: 7,
          repsLabel: "5-7",
          targetRPE: 8.5,
          restSeconds: 180,
          incrementKg: 2.5,
          roundToKg: 2.5,
          notes: "Target RPE 8-8.5. Do not go to failure.",
        }),
        exercise({
          id: "weighted-pull-ups-45deg-chin-ups",
          name: "Weighted Pull-Ups / 45 deg Chin-Ups",
          category: "compound",
          equipment: "bodyweight",
          muscleGroup: "Lats / Upper Back / Biceps",
          priority: "high",
          progressionType: "strength",
          sets: 4,
          repsMin: 6,
          repsMax: 8,
          repsLabel: "6-8",
          targetRPE: 8,
          restSeconds: [150, 180],
          loadType: "optionalExternal",
          weightMode: "additional load",
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "incline-dumbbell-press",
          name: "Incline Dumbbell Press",
          category: "compound",
          equipment: "dumbbell",
          muscleGroup: "Upper Chest",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 8,
          repsMax: 10,
          repsLabel: "8-10",
          targetRPE: 8.5,
          restSeconds: 120,
          weightMode: "per dumbbell",
          incrementKg: 2,
          roundToKg: 1,
          notes: "Target RPE 8-9.",
        }),
        exercise({
          id: "chest-supported-row",
          name: "Chest Supported Row",
          category: "compound",
          equipment: "machine",
          muscleGroup: "Upper Back",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 8,
          repsMax: 10,
          repsLabel: "8-10",
          targetRPE: 8.5,
          restSeconds: 120,
          incrementKg: 2.5,
          roundToKg: 2.5,
          notes: "Target RPE 8-9.",
        }),
        exercise({
          id: "machine-chest-press",
          name: "Machine Chest Press",
          category: "compound",
          equipment: "machine",
          muscleGroup: "Chest",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 2,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10-12",
          targetRPE: 8.5,
          restSeconds: 90,
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "neutral-mag-lat-pulldown",
          name: "Neutral / MAG Lat Pulldown",
          category: "compound",
          equipment: "cable",
          muscleGroup: "Lats / Back Width",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 2,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10-12",
          targetRPE: 8.5,
          restSeconds: 90,
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "cable-crunch",
          name: "Cable Crunch",
          category: "core",
          equipment: "cable",
          muscleGroup: "Core",
          priority: "medium",
          progressionType: "core",
          sets: 3,
          repsMin: 12,
          repsMax: 15,
          repsLabel: "12-15",
          targetRPE: 8.5,
          restSeconds: 60,
          incrementKg: 2.5,
          roundToKg: 2.5,
          notes: "Target RPE 8-9.",
        }),
        exercise({
          id: "hanging-leg-raise",
          name: "Hanging Leg Raise",
          category: "core",
          equipment: "bodyweight",
          muscleGroup: "Core",
          priority: "medium",
          progressionType: "core",
          sets: 2,
          repsMin: 10,
          repsMax: 15,
          repsLabel: "10-15",
          targetRPE: 8,
          restSeconds: 60,
          loadType: "bodyweight",
        }),
      ],
    },
    {
      id: "aab-day-2",
      name: "Day 2 - Athletic Lower + Vertical",
      shortName: "Day 2",
      focus: "Athletic Lower + Vertical",
      type: "training",
      notes: "For explosive exercises, do not chase fatigue. If speed drops, the set is done.",
      warmup: {
        title: "Warm-up & Activation",
        items: [
          { id: "aab-day-2-warmup-1", name: "Ankle Rocks / Knee-to-Wall", prescription: "2 x 10 / side", notes: "Rest 30 sec", videoUrl: "" },
          { id: "aab-day-2-warmup-2", name: "90/90 Hip Switches", prescription: "2 x 8", notes: "Rest 30 sec", videoUrl: "" },
          { id: "aab-day-2-warmup-3", name: "Adductor Rock-Backs", prescription: "2 x 8 / side", notes: "Rest 30 sec", videoUrl: "" },
          { id: "aab-day-2-warmup-4", name: "Glute Bridge", prescription: "2 x 12", notes: "Rest 30-45 sec", videoUrl: "" },
          { id: "aab-day-2-warmup-5", name: "Lateral Band Walks", prescription: "2 x 10 / side", notes: "Rest 30-45 sec", videoUrl: "" },
          { id: "aab-day-2-warmup-6", name: "Bodyweight Split Squat", prescription: "1 x 8 / leg", notes: "Rest 45 sec", videoUrl: "" },
        ],
      },
      exercises: [
        exercise({
          id: "pogo-jumps",
          name: "Pogo Jumps",
          category: "athletic",
          equipment: "bodyweight",
          muscleGroup: "Ankles / Elasticity",
          priority: "medium",
          progressionType: "athletic",
          sets: 3,
          repsMin: 20,
          repsMax: 20,
          repsLabel: "20",
          targetRPE: 7,
          restSeconds: [45, 60],
          loadType: "bodyweight",
          notes: "Quality target. Speed and stiffness matter more than fatigue.",
        }),
        exercise({
          id: "box-jumps",
          name: "Box Jumps",
          category: "athletic",
          equipment: "bodyweight",
          muscleGroup: "Vertical Power",
          priority: "high",
          progressionType: "athletic",
          sets: 4,
          repsMin: 3,
          repsMax: 3,
          repsLabel: "3",
          targetRPE: 7,
          restSeconds: 90,
          loadType: "bodyweight",
          notes: "Explosive target. Stop when jump quality drops.",
        }),
        exercise({
          id: "hang-clean",
          name: "Hang Clean",
          category: "athletic",
          equipment: "barbell",
          muscleGroup: "Full Body Power",
          priority: "high",
          progressionType: "athletic",
          sets: 4,
          repsMin: 3,
          repsMax: 3,
          repsLabel: "3",
          targetRPE: 8,
          restSeconds: [120, 180],
          incrementKg: 2.5,
          roundToKg: 2.5,
          notes: "Target RPE 7-8. Prioritize crisp technique.",
        }),
        exercise({
          id: "bulgarian-split-squat",
          name: "Bulgarian Split Squat",
          category: "compound",
          equipment: "dumbbell",
          muscleGroup: "Quads / Glutes",
          priority: "medium",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 6,
          repsMax: 8,
          repsLabel: "6-8 / leg",
          targetRPE: 8,
          restSeconds: 120,
          weightMode: "per dumbbell",
          incrementKg: 2,
          roundToKg: 1,
        }),
        exercise({
          id: "romanian-deadlift",
          name: "Romanian Deadlift",
          category: "compound",
          equipment: "barbell",
          muscleGroup: "Hamstrings / Glutes",
          priority: "medium",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 6,
          repsMax: 8,
          repsLabel: "6-8",
          targetRPE: 8,
          restSeconds: [120, 180],
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "hack-squat",
          name: "Hack Squat",
          category: "compound",
          equipment: "machine",
          muscleGroup: "Quads",
          priority: "medium",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 8,
          repsMax: 10,
          repsLabel: "8-10",
          targetRPE: 8.5,
          restSeconds: 120,
          incrementKg: 2.5,
          roundToKg: 2.5,
          notes: "Target RPE 8-8.5.",
        }),
        exercise({
          id: "seated-lying-hamstring-curl",
          name: "Seated / Lying Hamstring Curl",
          category: "isolation",
          equipment: "machine",
          muscleGroup: "Hamstrings",
          priority: "medium",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10-12",
          targetRPE: 8.5,
          restSeconds: 90,
          incrementKg: 2.5,
          roundToKg: 2.5,
          notes: "Target RPE 8-9.",
        }),
        exercise({
          id: "standing-calf-raise",
          name: "Standing Calf Raise",
          category: "isolation",
          equipment: "machine",
          muscleGroup: "Calves",
          priority: "medium",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 12,
          repsMax: 15,
          repsLabel: "12-15",
          targetRPE: 8.5,
          restSeconds: 60,
          incrementKg: 2.5,
          roundToKg: 2.5,
          notes: "Target RPE 8-9.",
        }),
        exercise({
          id: "tibialis-raises",
          name: "Tibialis Raises",
          category: "isolation",
          equipment: "bodyweight",
          muscleGroup: "Tibialis",
          priority: "medium",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 15,
          repsMax: 20,
          repsLabel: "15-20",
          targetRPE: 8,
          restSeconds: 45,
          loadType: "optionalExternal",
          incrementKg: 1,
          roundToKg: 1,
          notes: "2-3 sets based on fatigue.",
        }),
        exercise({
          id: "copenhagen-plank",
          name: "Copenhagen Plank",
          category: "core",
          equipment: "bodyweight",
          muscleGroup: "Adductors / Core",
          priority: "medium",
          progressionType: "core",
          sets: 2,
          repsMin: 20,
          repsMax: 30,
          repsLabel: "20-30 sec / side",
          targetRPE: 8,
          restSeconds: [45, 60],
          loadType: "bodyweight",
          notes: "Control target.",
        }),
      ],
    },
    {
      id: "aab-day-3",
      name: "Day 3 - Back + Biceps + Muscle-Up Base",
      shortName: "Day 3",
      focus: "Back + Biceps + Muscle-Up Base",
      type: "training",
      notes: "For high pull-ups, focus on height and explosiveness, not ugly high reps.",
      warmup: {
        title: "Warm-up & Activation",
        items: [
          { id: "aab-day-3-warmup-1", name: "Wrist Circles + Wrist Prep", prescription: "1-2 min", notes: "No rest needed", videoUrl: "" },
          { id: "aab-day-3-warmup-2", name: "Dead Hang Relaxed", prescription: "2 x 20-30 sec", notes: "Rest 45 sec", videoUrl: "" },
          { id: "aab-day-3-warmup-3", name: "Scapular Pull-Ups", prescription: "2 x 8", notes: "Rest 45 sec", videoUrl: "" },
          { id: "aab-day-3-warmup-4", name: "Band Pull-Aparts", prescription: "2 x 15", notes: "Rest 30-45 sec", videoUrl: "" },
          { id: "aab-day-3-warmup-5", name: "Light Lat Pulldown / Band Pulldown", prescription: "1-2 x 12", notes: "Rest 45 sec", videoUrl: "" },
        ],
      },
      exercises: [
        exercise({
          id: "explosive-pull-ups-high-pull-ups",
          name: "Explosive Pull-Ups / High Pull-Ups",
          category: "athletic",
          equipment: "bodyweight",
          muscleGroup: "Lats / Upper Back / Biceps",
          priority: "high",
          progressionType: "athletic",
          sets: 4,
          repsMin: 3,
          repsMax: 5,
          repsLabel: "3-5",
          targetRPE: 7,
          restSeconds: 120,
          loadType: "bodyweight",
          notes: "Explosive target. Height and speed matter more than fatigue.",
        }),
        exercise({
          id: "low-bar-band-muscle-up-transition-drill",
          name: "Low Bar / Band Muscle-Up Transition Drill",
          category: "athletic",
          equipment: "bodyweight",
          muscleGroup: "Back / Chest / Triceps / Core",
          priority: "high",
          progressionType: "athletic",
          sets: 3,
          repsMin: 4,
          repsMax: 6,
          repsLabel: "4-6",
          targetRPE: 7,
          restSeconds: 90,
          loadType: "bodyweight",
          notes: "Technique target. Keep transitions clean.",
        }),
        exercise({
          id: "straight-bar-dips",
          name: "Straight Bar Dips",
          category: "compound",
          equipment: "bodyweight",
          muscleGroup: "Chest / Triceps",
          priority: "medium",
          progressionType: "strength",
          sets: 2,
          repsMin: 6,
          repsMax: 10,
          repsLabel: "6-10",
          targetRPE: 8,
          restSeconds: [90, 120],
          loadType: "optionalExternal",
          weightMode: "additional load",
          incrementKg: 2.5,
          roundToKg: 2.5,
          notes: "Target RPE 7.5-8.",
        }),
        exercise({
          id: "neutral-grip-lat-pulldown",
          name: "Neutral-Grip Lat Pulldown",
          category: "compound",
          equipment: "cable",
          muscleGroup: "Lats / Back Width",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10-12",
          targetRPE: 8.5,
          restSeconds: 90,
          incrementKg: 2.5,
          roundToKg: 2.5,
          notes: "Target RPE 8-9.",
        }),
        exercise({
          id: "single-arm-lat-pulldown",
          name: "Single-Arm Lat Pulldown",
          category: "compound",
          equipment: "cable",
          muscleGroup: "Lats",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10-12 / arm",
          targetRPE: 8.5,
          restSeconds: 90,
          incrementKg: 2.5,
          roundToKg: 2.5,
          notes: "Target RPE 8-9.",
        }),
        exercise({
          id: "chest-supported-dumbbell-row",
          name: "Chest Supported Dumbbell Row",
          category: "compound",
          equipment: "dumbbell",
          muscleGroup: "Upper Back / Lats",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10-12",
          targetRPE: 8.5,
          restSeconds: 90,
          weightMode: "per dumbbell",
          incrementKg: 2,
          roundToKg: 1,
          notes: "Target RPE 8-9.",
        }),
        exercise({
          id: "dumbbell-curl",
          name: "Dumbbell Curl",
          category: "isolation",
          equipment: "dumbbell",
          muscleGroup: "Biceps",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10-12",
          targetRPE: 9,
          restSeconds: 60,
          weightMode: "per dumbbell",
          incrementKg: 1,
          roundToKg: 1,
          notes: "Target RPE 8.5-9.",
        }),
        exercise({
          id: "hammer-curl",
          name: "Hammer Curl",
          category: "isolation",
          equipment: "dumbbell",
          muscleGroup: "Biceps / Brachialis",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 2,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10-12",
          targetRPE: 9,
          restSeconds: 60,
          weightMode: "per dumbbell",
          incrementKg: 1,
          roundToKg: 1,
          notes: "Target RPE 8.5-9.",
        }),
        exercise({
          id: "hollow-body-hold",
          name: "Hollow Body Hold",
          category: "core",
          equipment: "bodyweight",
          muscleGroup: "Core",
          priority: "medium",
          progressionType: "core",
          sets: 3,
          repsMin: 20,
          repsMax: 30,
          repsLabel: "20-30 sec",
          targetRPE: 8,
          restSeconds: 60,
          loadType: "bodyweight",
          notes: "Control target.",
        }),
      ],
    },
    {
      id: "aab-day-4",
      name: "Day 4 - Upper Hypertrophy",
      shortName: "Day 4",
      focus: "Upper Hypertrophy",
      type: "training",
      notes: "This is the look day. Control, stretch, pump, and clean form.",
      warmup: {
        title: "Warm-up & Activation",
        items: [
          { id: "aab-day-4-warmup-1", name: "Band Shoulder Pass-Throughs", prescription: "2 x 10", notes: "Rest 30 sec", videoUrl: "" },
          { id: "aab-day-4-warmup-2", name: "Wall Slides", prescription: "2 x 10", notes: "Rest 30 sec", videoUrl: "" },
          { id: "aab-day-4-warmup-3", name: "Face Pull Light", prescription: "2 x 12", notes: "Rest 30-45 sec", videoUrl: "" },
          { id: "aab-day-4-warmup-4", name: "Scapular Push-Ups", prescription: "1-2 x 10", notes: "Rest 30-45 sec", videoUrl: "" },
          { id: "aab-day-4-warmup-5", name: "Incline Press Warm-Up Sets", prescription: "2-3 progressive sets", notes: "Rest 60-90 sec", videoUrl: "" },
        ],
      },
      exercises: [
        exercise({
          id: "incline-smith-press",
          name: "Incline Smith Press",
          category: "compound",
          equipment: "smith",
          muscleGroup: "Upper Chest",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 4,
          repsMin: 8,
          repsMax: 10,
          repsLabel: "8-10",
          targetRPE: 8.5,
          restSeconds: 120,
          incrementKg: 2.5,
          roundToKg: 2.5,
          notes: "Target RPE 8-9.",
        }),
        exercise({
          id: "flat-dumbbell-press",
          name: "Flat Dumbbell Press",
          category: "compound",
          equipment: "dumbbell",
          muscleGroup: "Chest",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10-12",
          targetRPE: 8.5,
          restSeconds: 90,
          weightMode: "per dumbbell",
          incrementKg: 2,
          roundToKg: 1,
          notes: "Target RPE 8-9.",
        }),
        exercise({
          id: "pec-deck-machine-fly",
          name: "Pec Deck / Machine Fly",
          category: "isolation",
          equipment: "machine",
          muscleGroup: "Chest",
          priority: "high",
          progressionType: "pump",
          sets: 3,
          repsMin: 12,
          repsMax: 15,
          repsLabel: "12-15",
          targetRPE: 9,
          restSeconds: 60,
          incrementKg: 2.5,
          roundToKg: 2.5,
          notes: "Target RPE 8.5-9.",
        }),
        exercise({
          id: "seated-dumbbell-shoulder-press",
          name: "Seated Dumbbell Shoulder Press",
          category: "compound",
          equipment: "dumbbell",
          muscleGroup: "Delts",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 8,
          repsMax: 10,
          repsLabel: "8-10",
          targetRPE: 8.5,
          restSeconds: 120,
          weightMode: "per dumbbell",
          incrementKg: 2,
          roundToKg: 1,
          notes: "Target RPE 8-9.",
        }),
        exercise({
          id: "lateral-raises",
          name: "Lateral Raises",
          category: "isolation",
          equipment: "dumbbell",
          muscleGroup: "Side Delts",
          priority: "high",
          progressionType: "pump",
          sets: 4,
          repsMin: 12,
          repsMax: 20,
          repsLabel: "12-20",
          targetRPE: 9,
          restSeconds: 60,
          weightMode: "per dumbbell",
          incrementKg: 1,
          roundToKg: 1,
          notes: "Target RPE 8.5-9.",
        }),
        exercise({
          id: "rear-delt-fly-reverse-pec-deck",
          name: "Rear Delt Fly / Reverse Pec Deck",
          category: "isolation",
          equipment: "machine",
          muscleGroup: "Rear Delts",
          priority: "high",
          progressionType: "pump",
          sets: 3,
          repsMin: 12,
          repsMax: 15,
          repsLabel: "12-15",
          targetRPE: 9,
          restSeconds: 60,
          incrementKg: 2.5,
          roundToKg: 2.5,
          notes: "Target RPE 8.5-9.",
        }),
        exercise({
          id: "machine-row-chest-supported-row",
          name: "Machine Row / Chest Supported Row",
          category: "compound",
          equipment: "machine",
          muscleGroup: "Upper Back / Lats",
          priority: "medium",
          progressionType: "hypertrophy",
          sets: 2,
          repsMin: 12,
          repsMax: 12,
          repsLabel: "12",
          targetRPE: 8,
          restSeconds: 90,
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "overhead-rope-triceps-extension",
          name: "Overhead Rope Triceps Extension",
          category: "isolation",
          equipment: "cable",
          muscleGroup: "Triceps",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10-12",
          targetRPE: 9,
          restSeconds: [60, 75],
          incrementKg: 2.5,
          roundToKg: 2.5,
          notes: "Target RPE 8.5-9.",
        }),
        exercise({
          id: "decline-sit-ups-cable-abs",
          name: "Decline Sit-Ups / Cable Abs",
          category: "core",
          equipment: "bodyweight",
          muscleGroup: "Core",
          priority: "medium",
          progressionType: "core",
          sets: 3,
          repsMin: 12,
          repsMax: 15,
          repsLabel: "12-15",
          targetRPE: 8.5,
          restSeconds: [45, 60],
          loadType: "optionalExternal",
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
      ],
    },
    {
      id: "aab-day-5",
      name: "Day 5 - Arms + Delts + V-Taper",
      shortName: "Day 5",
      focus: "Arms + Delts + V-Taper",
      type: "training",
      notes: "If tired, remove Explosive Push-Ups or one isolation exercise, not dips/chin-ups.",
      warmup: {
        title: "Warm-up & Activation",
        items: [
          { id: "aab-day-5-warmup-1", name: "Wrist Prep", prescription: "1 min", notes: "No rest needed", videoUrl: "" },
          { id: "aab-day-5-warmup-2", name: "Dead Hang", prescription: "2 x 20-30 sec", notes: "Rest 45 sec", videoUrl: "" },
          { id: "aab-day-5-warmup-3", name: "Scapular Pull-Ups", prescription: "2 x 8", notes: "Rest 45 sec", videoUrl: "" },
          { id: "aab-day-5-warmup-4", name: "Band Lat Pulldown", prescription: "2 x 12", notes: "Rest 30-45 sec", videoUrl: "" },
          { id: "aab-day-5-warmup-5", name: "Cable / Band External Rotation", prescription: "2 x 12 / arm", notes: "Rest 30-45 sec", videoUrl: "" },
        ],
      },
      exercises: [
        exercise({
          id: "weighted-dips",
          name: "Weighted Dips",
          category: "compound",
          equipment: "bodyweight",
          muscleGroup: "Triceps / Chest",
          priority: "high",
          progressionType: "strength",
          sets: 3,
          repsMin: 6,
          repsMax: 8,
          repsLabel: "6-8",
          targetRPE: 8.5,
          restSeconds: [150, 180],
          loadType: "optionalExternal",
          weightMode: "additional load",
          incrementKg: 2.5,
          roundToKg: 2.5,
          notes: "Target RPE 8-8.5.",
        }),
        exercise({
          id: "chin-ups-45deg-grip",
          name: "Chin-Ups / 45 deg Grip Chin-Ups",
          category: "compound",
          equipment: "bodyweight",
          muscleGroup: "Lats / Biceps",
          priority: "high",
          progressionType: "strength",
          sets: 3,
          repsMin: 6,
          repsMax: 10,
          repsLabel: "6-10",
          targetRPE: 8.5,
          restSeconds: [120, 180],
          loadType: "optionalExternal",
          weightMode: "additional load",
          incrementKg: 2.5,
          roundToKg: 2.5,
          notes: "Target RPE 8-8.5.",
        }),
        exercise({
          id: "seated-dumbbell-shoulder-press",
          name: "Seated Dumbbell Shoulder Press",
          category: "compound",
          equipment: "dumbbell",
          muscleGroup: "Delts",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 8,
          repsMax: 10,
          repsLabel: "8-10",
          targetRPE: 8.5,
          restSeconds: 120,
          weightMode: "per dumbbell",
          incrementKg: 2,
          roundToKg: 1,
          notes: "Target RPE 8-9.",
        }),
        exercise({
          id: "heavy-lateral-raises",
          name: "Heavy Lateral Raises",
          category: "isolation",
          equipment: "dumbbell",
          muscleGroup: "Side Delts",
          priority: "high",
          progressionType: "pump",
          sets: 4,
          repsMin: 10,
          repsMax: 15,
          repsLabel: "10-15",
          targetRPE: 9,
          restSeconds: [60, 75],
          weightMode: "per dumbbell",
          incrementKg: 1,
          roundToKg: 1,
          notes: "Target RPE 8.5-9.",
        }),
        exercise({
          id: "preacher-curl",
          name: "Preacher Curl",
          category: "isolation",
          equipment: "machine",
          muscleGroup: "Biceps",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10-12",
          targetRPE: 9,
          restSeconds: [60, 90],
          incrementKg: 2.5,
          roundToKg: 2.5,
          notes: "Target RPE 8.5-9.",
        }),
        exercise({
          id: "incline-dumbbell-curl",
          name: "Incline Dumbbell Curl",
          category: "isolation",
          equipment: "dumbbell",
          muscleGroup: "Biceps",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 12,
          repsMax: 15,
          repsLabel: "12-15",
          targetRPE: 9,
          restSeconds: 60,
          weightMode: "per dumbbell",
          incrementKg: 1,
          roundToKg: 1,
          notes: "Target RPE 8.5-9.",
        }),
        exercise({
          id: "skull-crushers",
          name: "Skull Crushers",
          category: "isolation",
          equipment: "barbell",
          muscleGroup: "Triceps",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10-12",
          targetRPE: 9,
          restSeconds: [60, 90],
          incrementKg: 2.5,
          roundToKg: 2.5,
          notes: "Target RPE 8.5-9.",
        }),
        exercise({
          id: "rope-overhead-extension",
          name: "Rope Overhead Extension",
          category: "isolation",
          equipment: "cable",
          muscleGroup: "Triceps",
          priority: "high",
          progressionType: "pump",
          sets: 2,
          repsMin: 12,
          repsMax: 15,
          repsLabel: "12-15",
          targetRPE: 9,
          restSeconds: 60,
          incrementKg: 2.5,
          roundToKg: 2.5,
          notes: "Target RPE 8.5-9.",
        }),
        exercise({
          id: "explosive-push-ups",
          name: "Explosive Push-Ups",
          category: "athletic",
          equipment: "bodyweight",
          muscleGroup: "Upper Power",
          priority: "medium",
          progressionType: "athletic",
          sets: 3,
          repsMin: 5,
          repsMax: 8,
          repsLabel: "5-8",
          targetRPE: 7,
          restSeconds: [60, 90],
          loadType: "bodyweight",
          notes: "2-3 sets. Explosive target; do not chase fatigue.",
        }),
        exercise({
          id: "plank",
          name: "Plank",
          category: "core",
          equipment: "bodyweight",
          muscleGroup: "Core",
          priority: "medium",
          progressionType: "core",
          sets: 3,
          repsMin: 45,
          repsMax: 60,
          repsLabel: "45-60 sec",
          targetRPE: 8,
          restSeconds: [45, 60],
          loadType: "bodyweight",
          notes: "Control target.",
        }),
      ],
    },
    {
      id: "aab-day-6",
      name: "Day 6 - Optional Lower Athletic Micro-Day",
      shortName: "Day 6",
      focus: "Optional Lower Athletic Micro-Day",
      type: "training",
      isOptional: true,
      notes: "Day 6 is optional. You should leave fresher, not destroyed.",
      warmup: {
        title: "Warm-up & Activation",
        items: [
          { id: "aab-day-6-warmup-1", name: "Ankle Rocks", prescription: "2 x 10", notes: "Rest 30 sec", videoUrl: "" },
          { id: "aab-day-6-warmup-2", name: "Hip Openers", prescription: "1-2 min", notes: "No rest needed", videoUrl: "" },
          { id: "aab-day-6-warmup-3", name: "Glute Bridge", prescription: "2 x 12", notes: "Rest 30-45 sec", videoUrl: "" },
          { id: "aab-day-6-warmup-4", name: "Bodyweight Lunges", prescription: "1 x 10 / leg", notes: "Rest 45 sec", videoUrl: "" },
        ],
      },
      exercises: [
        exercise({
          id: "low-pogo-jumps",
          name: "Low Pogo Jumps",
          category: "athletic",
          equipment: "bodyweight",
          muscleGroup: "Ankles / Elasticity",
          priority: "medium",
          progressionType: "athletic",
          sets: 2,
          repsMin: 20,
          repsMax: 20,
          repsLabel: "20",
          targetRPE: 7,
          restSeconds: 45,
          loadType: "bodyweight",
          notes: "Quality target. Keep this low fatigue.",
        }),
        exercise({
          id: "hip-thrust-glute-bridge-machine",
          name: "Hip Thrust / Glute Bridge Machine",
          category: "compound",
          equipment: "machine",
          muscleGroup: "Glutes / Hamstrings",
          priority: "medium",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 8,
          repsMax: 10,
          repsLabel: "8-10",
          targetRPE: 8,
          restSeconds: 90,
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "reverse-lunges-walking-lunges",
          name: "Reverse Lunges / Walking Lunges",
          category: "compound",
          equipment: "dumbbell",
          muscleGroup: "Glutes / Quads",
          priority: "medium",
          progressionType: "hypertrophy",
          sets: 2,
          repsMin: 10,
          repsMax: 10,
          repsLabel: "10 / leg",
          targetRPE: 8,
          restSeconds: 90,
          weightMode: "per dumbbell",
          incrementKg: 2,
          roundToKg: 1,
        }),
        exercise({
          id: "hamstring-curl",
          name: "Hamstring Curl",
          category: "isolation",
          equipment: "machine",
          muscleGroup: "Hamstrings",
          priority: "medium",
          progressionType: "hypertrophy",
          sets: 2,
          repsMin: 12,
          repsMax: 12,
          repsLabel: "12",
          targetRPE: 8,
          restSeconds: 60,
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "standing-calf-raise",
          name: "Standing Calf Raise",
          category: "isolation",
          equipment: "machine",
          muscleGroup: "Calves",
          priority: "medium",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 12,
          repsMax: 15,
          repsLabel: "12-15",
          targetRPE: 8.5,
          restSeconds: 60,
          incrementKg: 2.5,
          roundToKg: 2.5,
          notes: "Target RPE 8-9.",
        }),
        exercise({
          id: "tibialis-raises",
          name: "Tibialis Raises",
          category: "isolation",
          equipment: "bodyweight",
          muscleGroup: "Tibialis",
          priority: "medium",
          progressionType: "hypertrophy",
          sets: 2,
          repsMin: 15,
          repsMax: 20,
          repsLabel: "15-20",
          targetRPE: 8,
          restSeconds: 45,
          loadType: "optionalExternal",
          incrementKg: 1,
          roundToKg: 1,
        }),
        exercise({
          id: "copenhagen-plank",
          name: "Copenhagen Plank",
          category: "core",
          equipment: "bodyweight",
          muscleGroup: "Adductors / Core",
          priority: "medium",
          progressionType: "core",
          sets: 2,
          repsMin: 20,
          repsMax: 30,
          repsLabel: "20-30 sec / side",
          targetRPE: 8,
          restSeconds: 45,
          loadType: "bodyweight",
          notes: "Control target.",
        }),
      ],
    },
  ],
};

export function getProgramDay(dayId) {
  return workoutProgram.days.find((day) => day.id === dayId) ?? workoutProgram.days[0];
}

export function getExercise(day, exerciseId) {
  return day.exercises.find((exercise) => exercise.id === exerciseId);
}
