const shared = {
  targetRPE: 8,
  recommendedWeight: null,
};

function exercise({
  id,
  name,
  category,
  equipment,
  muscleGroup,
  priority,
  progressionType,
  sets,
  repsMin,
  repsMax,
  repsLabel,
  restSeconds,
  loadType = "external",
  weightMode = "kg",
  incrementKg,
  roundToKg,
  targetRPE = shared.targetRPE,
  recommendedWeight = shared.recommendedWeight,
}) {
  return {
    id,
    name,
    category,
    equipment,
    muscleGroup,
    priority,
    progressionType,
    sets,
    repsMin,
    repsMax,
    repsLabel,
    targetRPE,
    restSeconds,
    recommendedWeight,
    loadType,
    weightMode,
    incrementKg,
    roundToKg,
  };
}

export const workoutProgram = {
  name: "Athletic Bodybuilding RPE Program",
  version: "2.0.0",
  cycleOrder: ["day-1", "day-2", "day-3", "day-4", "day-5"],
  days: [
    {
      id: "day-1",
      name: "Day 1 — Chest + Back Power",
      shortName: "Day 1",
      focus: "Chest + Back Power",
      type: "training",
      exercises: [
        exercise({
          id: "bench-press",
          name: "Bench Press",
          category: "compound",
          equipment: "barbell",
          muscleGroup: "Chest",
          priority: "high",
          progressionType: "strength",
          sets: 4,
          repsMin: 5,
          repsMax: 7,
          repsLabel: "5–7",
          restSeconds: 180,
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "weighted-pull-ups",
          name: "Weighted Pull-Ups",
          category: "compound",
          equipment: "bodyweight",
          muscleGroup: "Lats / Back Width",
          priority: "high",
          progressionType: "strength",
          sets: 4,
          repsMin: 6,
          repsMax: 8,
          repsLabel: "6–8",
          restSeconds: [150, 180],
          loadType: "optionalExternal",
          weightMode: "additional load",
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "incline-dumbbell-press",
          name: "Incline Dumbbell Press",
          category: "compound",
          equipment: "dumbbell",
          muscleGroup: "Upper Chest",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 4,
          repsMin: 8,
          repsMax: 10,
          repsLabel: "8–10",
          restSeconds: 120,
          weightMode: "per dumbbell",
          incrementKg: 2,
          roundToKg: 1,
        }),
        exercise({
          id: "chest-supported-row",
          name: "Chest Supported Row",
          category: "compound",
          equipment: "machine",
          muscleGroup: "Upper Back",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 4,
          repsMin: 8,
          repsMax: 10,
          repsLabel: "8–10",
          restSeconds: 120,
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "machine-chest-press",
          name: "Machine Chest Press",
          category: "compound",
          equipment: "machine",
          muscleGroup: "Chest",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10–12",
          restSeconds: 90,
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "lat-pulldown",
          name: "Lat Pulldown",
          category: "compound",
          equipment: "cable",
          muscleGroup: "Lats / Back Width",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10–12",
          restSeconds: 90,
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "dips",
          name: "Dips",
          category: "compound",
          equipment: "bodyweight",
          muscleGroup: "Chest / Triceps",
          priority: "medium",
          progressionType: "hypertrophy",
          sets: 2,
          repsMin: null,
          repsMax: null,
          repsLabel: "failure",
          restSeconds: 120,
          loadType: "optionalExternal",
          weightMode: "additional load",
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "hanging-leg-raise",
          name: "Hanging Leg Raise",
          category: "core",
          equipment: "bodyweight",
          muscleGroup: "Core",
          priority: "medium",
          progressionType: "core",
          sets: 3,
          repsMin: 12,
          repsMax: 15,
          repsLabel: "12–15",
          restSeconds: 45,
          loadType: "bodyweight",
        }),
        exercise({
          id: "cable-crunch",
          name: "Cable Crunch",
          category: "core",
          equipment: "cable",
          muscleGroup: "Core",
          priority: "medium",
          progressionType: "core",
          sets: 3,
          repsMin: 15,
          repsMax: 15,
          repsLabel: "15",
          restSeconds: 45,
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
      ],
    },
    {
      id: "day-2",
      name: "Day 2 — Athletic Lower + Vertical",
      shortName: "Day 2",
      focus: "Athletic Lower + Vertical",
      type: "training",
      exercises: [
        exercise({
          id: "pogo-jumps",
          name: "Pogo Jumps",
          category: "athletic",
          equipment: "bodyweight",
          muscleGroup: "Ankles / Elasticity",
          priority: "medium",
          progressionType: "athletic",
          sets: 3,
          repsMin: 20,
          repsMax: 20,
          repsLabel: "20",
          restSeconds: 60,
          loadType: "bodyweight",
        }),
        exercise({
          id: "box-jumps",
          name: "Box Jumps",
          category: "athletic",
          equipment: "bodyweight",
          muscleGroup: "Vertical Power",
          priority: "high",
          progressionType: "athletic",
          sets: 4,
          repsMin: 3,
          repsMax: 3,
          repsLabel: "3",
          restSeconds: 90,
          loadType: "bodyweight",
        }),
        exercise({
          id: "hang-cleans",
          name: "Hang Cleans",
          category: "athletic",
          equipment: "barbell",
          muscleGroup: "Full Body Power",
          priority: "high",
          progressionType: "athletic",
          sets: 4,
          repsMin: 3,
          repsMax: 5,
          repsLabel: "3–5",
          restSeconds: [120, 180],
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "bulgarian-split-squat",
          name: "Bulgarian Split Squat",
          category: "compound",
          equipment: "dumbbell",
          muscleGroup: "Quads / Glutes",
          priority: "medium",
          progressionType: "hypertrophy",
          sets: 4,
          repsMin: 8,
          repsMax: 8,
          repsLabel: "8",
          restSeconds: 120,
          weightMode: "per dumbbell",
          incrementKg: 2,
          roundToKg: 1,
        }),
        exercise({
          id: "romanian-deadlift",
          name: "Romanian Deadlift",
          category: "compound",
          equipment: "barbell",
          muscleGroup: "Hamstrings / Glutes",
          priority: "medium",
          progressionType: "hypertrophy",
          sets: 4,
          repsMin: 8,
          repsMax: 8,
          repsLabel: "8",
          restSeconds: [120, 180],
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "hack-squat",
          name: "Hack Squat",
          category: "compound",
          equipment: "machine",
          muscleGroup: "Quads",
          priority: "medium",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 10,
          repsLabel: "10",
          restSeconds: 120,
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "hamstring-curl",
          name: "Hamstring Curl",
          category: "isolation",
          equipment: "machine",
          muscleGroup: "Hamstrings",
          priority: "medium",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10–12",
          restSeconds: 90,
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "standing-calf-raise",
          name: "Standing Calf Raise",
          category: "isolation",
          equipment: "machine",
          muscleGroup: "Calves",
          priority: "medium",
          progressionType: "hypertrophy",
          sets: 4,
          repsMin: 12,
          repsMax: 15,
          repsLabel: "12–15",
          restSeconds: 60,
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "tibialis-raises",
          name: "Tibialis Raises",
          category: "isolation",
          equipment: "bodyweight",
          muscleGroup: "Tibialis",
          priority: "medium",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 15,
          repsMax: 20,
          repsLabel: "15–20",
          restSeconds: 45,
          loadType: "optionalExternal",
          incrementKg: 1,
          roundToKg: 1,
        }),
        exercise({
          id: "copenhagen-plank",
          name: "Copenhagen Plank",
          category: "core",
          equipment: "bodyweight",
          muscleGroup: "Adductors / Core",
          priority: "medium",
          progressionType: "core",
          sets: 3,
          repsMin: null,
          repsMax: null,
          repsLabel: "timed sets",
          restSeconds: 45,
          loadType: "bodyweight",
        }),
      ],
    },
    {
      id: "day-3",
      name: "Day 3 — Rest / Basketball / Mobility",
      shortName: "Day 3",
      focus: "Rest / Basketball / Mobility",
      type: "recovery",
      activities: ["Light Basketball", "Mobility", "Stretching", "Recovery work", "Optional Abs"],
      exercises: [],
    },
    {
      id: "day-4",
      name: "Day 4 — Upper Hypertrophy",
      shortName: "Day 4",
      focus: "Upper Hypertrophy",
      type: "training",
      exercises: [
        exercise({
          id: "incline-smith-press",
          name: "Incline Smith Press",
          category: "compound",
          equipment: "smith",
          muscleGroup: "Upper Chest",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 4,
          repsMin: 8,
          repsMax: 10,
          repsLabel: "8–10",
          restSeconds: 120,
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "flat-dumbbell-press",
          name: "Flat Dumbbell Press",
          category: "compound",
          equipment: "dumbbell",
          muscleGroup: "Chest",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10–12",
          restSeconds: 90,
          weightMode: "per dumbbell",
          incrementKg: 2,
          roundToKg: 1,
        }),
        exercise({
          id: "pec-deck-machine-fly",
          name: "Pec Deck / Machine Fly",
          category: "isolation",
          equipment: "machine",
          muscleGroup: "Chest",
          priority: "high",
          progressionType: "pump",
          sets: 3,
          repsMin: 12,
          repsMax: 15,
          repsLabel: "12–15",
          restSeconds: [60, 75],
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "neutral-grip-lat-pulldown",
          name: "Neutral Grip Lat Pulldown",
          category: "compound",
          equipment: "cable",
          muscleGroup: "Lats / Back Width",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 4,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10–12",
          restSeconds: 90,
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "single-arm-row",
          name: "Single Arm Row",
          category: "compound",
          equipment: "dumbbell",
          muscleGroup: "Back",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 10,
          repsLabel: "10",
          restSeconds: 90,
          weightMode: "per dumbbell",
          incrementKg: 2,
          roundToKg: 1,
        }),
        exercise({
          id: "lateral-raises",
          name: "Lateral Raises",
          category: "isolation",
          equipment: "dumbbell",
          muscleGroup: "Side Delts",
          priority: "high",
          progressionType: "pump",
          sets: 5,
          repsMin: 12,
          repsMax: 15,
          repsLabel: "12–15",
          restSeconds: 60,
          weightMode: "per dumbbell",
          incrementKg: 1,
          roundToKg: 1,
        }),
        exercise({
          id: "rear-delt-fly",
          name: "Rear Delt Fly",
          category: "isolation",
          equipment: "machine",
          muscleGroup: "Rear Delts",
          priority: "high",
          progressionType: "pump",
          sets: 4,
          repsMin: 15,
          repsMax: 15,
          repsLabel: "15",
          restSeconds: 60,
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "ez-bar-curl",
          name: "EZ Bar Curl",
          category: "isolation",
          equipment: "barbell",
          muscleGroup: "Biceps",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 10,
          repsLabel: "10",
          restSeconds: [60, 90],
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "hammer-curl",
          name: "Hammer Curl",
          category: "isolation",
          equipment: "dumbbell",
          muscleGroup: "Biceps / Brachialis",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 12,
          repsMax: 12,
          repsLabel: "12",
          restSeconds: 60,
          weightMode: "per dumbbell",
          incrementKg: 1,
          roundToKg: 1,
        }),
        exercise({
          id: "overhead-tricep-extension",
          name: "Overhead Tricep Extension",
          category: "isolation",
          equipment: "cable",
          muscleGroup: "Triceps",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10–12",
          restSeconds: [60, 75],
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "decline-sit-ups-cable-abs",
          name: "Decline Sit-Ups / Cable Abs",
          category: "core",
          equipment: "bodyweight",
          muscleGroup: "Core",
          priority: "medium",
          progressionType: "core",
          sets: 3,
          repsMin: 15,
          repsMax: 15,
          repsLabel: "15",
          restSeconds: 45,
          loadType: "optionalExternal",
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
      ],
    },
    {
      id: "day-5",
      name: "Day 5 — Arms + Delts + Athletic Upper",
      shortName: "Day 5",
      focus: "Arms + Delts + Athletic Upper",
      type: "training",
      exercises: [
        exercise({
          id: "weighted-dips",
          name: "Weighted Dips",
          category: "compound",
          equipment: "bodyweight",
          muscleGroup: "Triceps / Chest",
          priority: "high",
          progressionType: "strength",
          sets: 4,
          repsMin: 6,
          repsMax: 8,
          repsLabel: "6–8",
          restSeconds: [150, 180],
          loadType: "optionalExternal",
          weightMode: "additional load",
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "chin-ups",
          name: "Chin-Ups",
          category: "compound",
          equipment: "bodyweight",
          muscleGroup: "Lats / Biceps",
          priority: "high",
          progressionType: "strength",
          sets: 4,
          repsMin: 6,
          repsMax: 10,
          repsLabel: "6–10",
          restSeconds: [120, 180],
          loadType: "optionalExternal",
          weightMode: "additional load",
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "seated-dumbbell-shoulder-press",
          name: "Seated Dumbbell Shoulder Press",
          category: "compound",
          equipment: "dumbbell",
          muscleGroup: "Delts",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 4,
          repsMin: 8,
          repsMax: 10,
          repsLabel: "8–10",
          restSeconds: 120,
          weightMode: "per dumbbell",
          incrementKg: 2,
          roundToKg: 1,
        }),
        exercise({
          id: "heavy-lateral-raises",
          name: "Heavy Lateral Raises",
          category: "isolation",
          equipment: "dumbbell",
          muscleGroup: "Side Delts",
          priority: "high",
          progressionType: "pump",
          sets: 4,
          repsMin: 12,
          repsMax: 15,
          repsLabel: "12–15",
          restSeconds: [60, 75],
          weightMode: "per dumbbell",
          incrementKg: 1,
          roundToKg: 1,
        }),
        exercise({
          id: "preacher-curl",
          name: "Preacher Curl",
          category: "isolation",
          equipment: "machine",
          muscleGroup: "Biceps",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10–12",
          restSeconds: [60, 90],
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "incline-dumbbell-curl",
          name: "Incline Dumbbell Curl",
          category: "isolation",
          equipment: "dumbbell",
          muscleGroup: "Biceps",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 12,
          repsMax: 15,
          repsLabel: "12–15",
          restSeconds: 60,
          weightMode: "per dumbbell",
          incrementKg: 1,
          roundToKg: 1,
        }),
        exercise({
          id: "skull-crushers",
          name: "Skull Crushers",
          category: "isolation",
          equipment: "barbell",
          muscleGroup: "Triceps",
          priority: "high",
          progressionType: "hypertrophy",
          sets: 3,
          repsMin: 10,
          repsMax: 12,
          repsLabel: "10–12",
          restSeconds: [60, 90],
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "rope-overhead-extension",
          name: "Rope Overhead Extension",
          category: "isolation",
          equipment: "cable",
          muscleGroup: "Triceps",
          priority: "high",
          progressionType: "pump",
          sets: 3,
          repsMin: 12,
          repsMax: 15,
          repsLabel: "12–15",
          restSeconds: [45, 75],
          incrementKg: 2.5,
          roundToKg: 2.5,
        }),
        exercise({
          id: "explosive-push-ups",
          name: "Explosive Push-Ups",
          category: "athletic",
          equipment: "bodyweight",
          muscleGroup: "Upper Power",
          priority: "medium",
          progressionType: "athletic",
          sets: 3,
          repsMin: 5,
          repsMax: 8,
          repsLabel: "5–8",
          restSeconds: [60, 90],
          loadType: "bodyweight",
        }),
        exercise({
          id: "plank",
          name: "Plank",
          category: "core",
          equipment: "bodyweight",
          muscleGroup: "Core",
          priority: "medium",
          progressionType: "core",
          sets: 3,
          repsMin: 60,
          repsMax: 60,
          repsLabel: "60 sec",
          restSeconds: [45, 60],
          loadType: "bodyweight",
        }),
      ],
    },
  ],
};

export function getProgramDay(dayId) {
  return workoutProgram.days.find((day) => day.id === dayId) ?? workoutProgram.days[0];
}

export function getExercise(day, exerciseId) {
  return day.exercises.find((exercise) => exercise.id === exerciseId);
}
